### ISSUE TITLE
为什么我action执行成功了但是没有签到成功

### ISSUE THREAD

**Issue by Endwas** [fgr178707/aliyunpan-automation#15]
在app里面看签到还是待签到 但是action是success的了

**Comment by fgr178707** [comment]
> 在app里面看签到还是待签到 但是action是success的了

看了一下你的运行日志
这地方提示报错，你重新填写一下access token
![image](https://github.com/fgr178707/aliyunpan-automation/assets/109357981/51f87b6d-613d-480b-92ab-4787c6022fc8)

如需远程帮助，请加微信:fgr1787076

**Comment by Endwas** [comment]
@fgr178707 能否弄个补偿的机制，阿里云请求rate limit能重试。。

**Comment by fgr178707** [comment]
> @fgr178707 能否弄个补偿的机制，阿里云请求rate limit能重试。。

请查看隔壁仓库 https://github.com/fgr178707/aliyunpan
