### ISSUE TITLE
报错如下，这是什么原因

### ISSUE THREAD

**Issue by wangkerong** [fgr178707/aliyunpan-automation#16]
签到成功了，消息推送也成功了，但是推送的消息里面有error如图，这是哪里没设置好嘛？
![image](https://github.com/fgr178707/aliyunpan-automation/assets/44842104/121dac2b-b43b-4aa4-ba7f-e3778d98b279)

**Comment by fgr178707** [comment]
> 签到成功了，消息推送也成功了，但是推送的消息里面有error如图，这是哪里没设置好嘛？ ![image](https://user-images.githubusercontent.com/44842104/244609566-121dac2b-b43b-4aa4-ba7f-e3778d98b279.png)

重新填写 GP_TOKEN
[GP_TOKEN 获取方法](https://github.com/fgr178707/aliyunpan-automation/wiki/GP_TOKEN-获取方法)

**Comment by wangkerong** [comment]
已解决，感谢！
