### ISSUE TITLE
第2步点击：选择你复制的这个仓库 Settings

### ISSUE THREAD

**Issue by DongLichat** [fgr178707/aliyunpan-automation#8]
这个setting选项找不到，在[Insights]后面没有了

**Comment by chatgpted** [comment]
点fork，再到自己仓库就有了，我也是这步困扰好久，后面去问问就知道了，纯小白

**Comment by DongLichat** [comment]
> 点fork，再到自己仓库就有了，我也是这步困扰好久，后面去问问就知道了，纯小白

我也是小白，刚才仔细看了下说明，发现忘了fork这一步。现在弄好了

**Comment by fgr178707** [comment]
> 点fork，再到自己仓库就有了，我也是这步困扰好久，后面去问问就知道了，纯小白

已经在wikli里边进行修改了
